vscode:
  extensions:
    - esbenp.prettier-vscode@3.2.1:8tE6frXOvsWQ9kRk24kSgw==
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - ms-vsliveshare.vsliveshare-pack@0.3.4:SHAGljo8pKUdyOKmsw+SXw==